version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: helpdesk_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
